create extension if not exists pgcrypto;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to anon, authenticated;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'viewer' check (role in ('viewer', 'staff', 'admin', 'owner')),
  created_at timestamptz not null default now()
);

create or replace function private.is_admin(user_id uuid default auth.uid())
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = user_id
      and role in ('owner', 'admin')
  );
$$;

grant execute on function private.is_admin(uuid) to anon, authenticated;

create or replace function private.has_staff_access(user_id uuid default auth.uid())
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = user_id
      and role in ('owner', 'admin', 'staff')
  );
$$;

grant execute on function private.has_staff_access(uuid) to anon, authenticated;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'viewer')
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

create table if not exists public.menu_sections (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  description text,
  display_mode text not null check (display_mode in ('compact-list', 'recipe-cards', 'grouped-by-base')),
  price_idr integer,
  sort_order integer not null default 999,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_entries (
  id uuid primary key default gen_random_uuid(),
  section_id uuid not null references public.menu_sections(id) on delete cascade,
  name text not null,
  ingredients text[] not null default '{}',
  base_name text,
  benefit text,
  mix_notes jsonb not null default '{}'::jsonb,
  mix_image_urls jsonb not null default '{}'::jsonb,
  mix_availability jsonb not null default '{}'::jsonb,
  category_slug text check (category_slug in ('roots-detox', 'vitamin-c-booster', 'hydration')),
  image_url text,
  accent_color text not null default '#1f7a4d',
  price_idr integer,
  sort_order integer not null default 999,
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists menu_entries_section_sort_idx on public.menu_entries(section_id, sort_order);
create index if not exists menu_entries_base_idx on public.menu_entries(base_name);

create table if not exists public.dining_tables (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  qr_token text not null unique default replace(gen_random_uuid()::text, '-', ''),
  label text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.table_sessions (
  id uuid primary key default gen_random_uuid(),
  table_id uuid not null references public.dining_tables(id),
  status text not null default 'active' check (status in ('active', 'closed', 'canceled')),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  session_id uuid references public.table_sessions(id),
  order_number bigint generated by default as identity,
  table_id uuid not null references public.dining_tables(id),
  customer_name text,
  notes text,
  cancel_reason text,
  status text not null default 'new' check (status in ('new', 'preparing', 'ready', 'completed', 'canceled')),
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid', 'pending', 'paid', 'failed', 'expired', 'refunded')),
  payment_method text,
  paid_at timestamptz,
  subtotal_idr integer not null default 0,
  business_date date not null default (timezone('Asia/Jakarta', now())::date),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_entry_id uuid references public.menu_entries(id) on delete set null,
  item_name text not null,
  variant_label text,
  quantity integer not null check (quantity > 0 and quantity <= 99),
  unit_price_idr integer not null check (unit_price_idr >= 0),
  line_total_idr integer not null check (line_total_idr >= 0),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  provider text not null default 'manual',
  provider_reference text,
  method text,
  status text not null default 'pending' check (status in ('pending', 'paid', 'failed', 'expired', 'refunded')),
  amount_idr integer not null check (amount_idr >= 0),
  currency text not null default 'IDR',
  checkout_url text,
  qr_string text,
  raw_payload jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  action text not null,
  entity_type text not null,
  entity_id uuid,
  actor_type text not null default 'system' check (actor_type in ('customer', 'admin', 'system')),
  actor_user_id uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists dining_tables_code_idx on public.dining_tables(code);
create unique index if not exists dining_tables_qr_token_idx on public.dining_tables(qr_token);
create index if not exists table_sessions_table_status_idx on public.table_sessions(table_id, status, opened_at);
create index if not exists orders_status_created_idx on public.orders(status, created_at);
create index if not exists orders_payment_status_created_idx on public.orders(payment_status, created_at);
create index if not exists orders_table_created_idx on public.orders(table_id, created_at);
create index if not exists orders_session_idx on public.orders(session_id);
create index if not exists orders_business_date_idx on public.orders(business_date, status, payment_status);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists payments_order_created_idx on public.payments(order_id, created_at);
create index if not exists payments_provider_reference_idx on public.payments(provider, provider_reference);
create index if not exists audit_logs_created_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_entity_idx on public.audit_logs(entity_type, entity_id);

grant select on public.menu_sections to anon, authenticated;
grant select on public.menu_entries to anon, authenticated;
grant select on public.profiles to authenticated;
grant insert, update, delete on public.menu_sections to authenticated;
grant insert, update, delete on public.menu_entries to authenticated;
grant update on public.profiles to authenticated;
revoke select on public.dining_tables from anon;
grant select on public.dining_tables to authenticated;
grant select, update on public.table_sessions to authenticated;
grant insert, update on public.dining_tables to authenticated;
grant select, update on public.orders to authenticated;
grant select on public.order_items to authenticated;
grant select, insert, update on public.payments to authenticated;
grant select, insert on public.audit_logs to authenticated;
grant usage, select on sequence public.orders_order_number_seq to authenticated;

insert into storage.buckets (id, name, public)
values ('menu-images', 'menu-images', true)
on conflict (id) do update set public = true;

drop policy if exists "public can read menu images" on storage.objects;
create policy "public can read menu images"
on storage.objects for select
using (bucket_id = 'menu-images');

drop policy if exists "admins can insert menu images" on storage.objects;
create policy "admins can insert menu images"
on storage.objects for insert
with check (bucket_id = 'menu-images' and private.is_admin());

drop policy if exists "admins can update menu images" on storage.objects;
create policy "admins can update menu images"
on storage.objects for update
using (bucket_id = 'menu-images' and private.is_admin())
with check (bucket_id = 'menu-images' and private.is_admin());

drop policy if exists "admins can delete menu images" on storage.objects;
create policy "admins can delete menu images"
on storage.objects for delete
using (bucket_id = 'menu-images' and private.is_admin());

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_menu_sections_updated_at on public.menu_sections;
create trigger touch_menu_sections_updated_at
before update on public.menu_sections
for each row execute function public.touch_updated_at();

drop trigger if exists touch_menu_entries_updated_at on public.menu_entries;
create trigger touch_menu_entries_updated_at
before update on public.menu_entries
for each row execute function public.touch_updated_at();

drop trigger if exists touch_dining_tables_updated_at on public.dining_tables;
create trigger touch_dining_tables_updated_at
before update on public.dining_tables
for each row execute function public.touch_updated_at();

drop trigger if exists touch_table_sessions_updated_at on public.table_sessions;
create trigger touch_table_sessions_updated_at
before update on public.table_sessions
for each row execute function public.touch_updated_at();

drop trigger if exists touch_orders_updated_at on public.orders;
create trigger touch_orders_updated_at
before update on public.orders
for each row execute function public.touch_updated_at();

drop trigger if exists touch_payments_updated_at on public.payments;
create trigger touch_payments_updated_at
before update on public.payments
for each row execute function public.touch_updated_at();

alter table public.profiles enable row level security;
alter table public.menu_sections enable row level security;
alter table public.menu_entries enable row level security;
alter table public.dining_tables enable row level security;
alter table public.table_sessions enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "profiles can read own profile" on public.profiles;
create policy "profiles can read own profile"
on public.profiles for select
using (id = auth.uid() or private.is_admin());

drop policy if exists "admins can update profiles" on public.profiles;
create policy "admins can update profiles"
on public.profiles for update
using (private.is_admin())
with check (private.is_admin());

drop policy if exists "public can read active sections" on public.menu_sections;
create policy "public can read active sections"
on public.menu_sections for select
using (is_active = true or private.is_admin());

drop policy if exists "admins can insert sections" on public.menu_sections;
create policy "admins can insert sections"
on public.menu_sections for insert
with check (private.is_admin());

drop policy if exists "admins can update sections" on public.menu_sections;
create policy "admins can update sections"
on public.menu_sections for update
using (private.is_admin())
with check (private.is_admin());

drop policy if exists "admins can delete sections" on public.menu_sections;
create policy "admins can delete sections"
on public.menu_sections for delete
using (private.is_admin());

drop policy if exists "public can read available entries" on public.menu_entries;
create policy "public can read available entries"
on public.menu_entries for select
using (
  private.is_admin()
  or (
    is_available = true
    and exists (
      select 1
      from public.menu_sections
      where menu_sections.id = menu_entries.section_id
        and menu_sections.is_active = true
    )
  )
);

drop policy if exists "admins can insert entries" on public.menu_entries;
create policy "admins can insert entries"
on public.menu_entries for insert
with check (private.is_admin());

drop policy if exists "admins can update entries" on public.menu_entries;
create policy "admins can update entries"
on public.menu_entries for update
using (private.is_admin())
with check (private.is_admin());

drop policy if exists "admins can delete entries" on public.menu_entries;
create policy "admins can delete entries"
on public.menu_entries for delete
using (private.is_admin());

drop policy if exists "public can read active dining tables" on public.dining_tables;
drop policy if exists "admins can read dining tables" on public.dining_tables;
create policy "admins can read dining tables"
on public.dining_tables for select
using (private.is_admin());

drop policy if exists "admins can insert dining tables" on public.dining_tables;
create policy "admins can insert dining tables"
on public.dining_tables for insert
with check (private.is_admin());

drop policy if exists "admins can update dining tables" on public.dining_tables;
create policy "admins can update dining tables"
on public.dining_tables for update
using (private.is_admin())
with check (private.is_admin());

drop policy if exists "admins can read table sessions" on public.table_sessions;
create policy "admins can read table sessions"
on public.table_sessions for select
using (private.is_admin());

drop policy if exists "admins can update table sessions" on public.table_sessions;
create policy "admins can update table sessions"
on public.table_sessions for update
using (private.is_admin())
with check (private.is_admin());

drop policy if exists "admins can read orders" on public.orders;
create policy "admins can read orders"
on public.orders for select
using (private.is_admin());

drop policy if exists "admins can update orders" on public.orders;
create policy "admins can update orders"
on public.orders for update
using (private.is_admin())
with check (private.is_admin());

drop policy if exists "admins can read order items" on public.order_items;
create policy "admins can read order items"
on public.order_items for select
using (private.is_admin());

drop policy if exists "admins can read payments" on public.payments;
create policy "admins can read payments"
on public.payments for select
using (private.is_admin());

drop policy if exists "admins can insert payments" on public.payments;
create policy "admins can insert payments"
on public.payments for insert
with check (private.is_admin());

drop policy if exists "admins can update payments" on public.payments;
create policy "admins can update payments"
on public.payments for update
using (private.is_admin())
with check (private.is_admin());

drop policy if exists "admins can read audit logs" on public.audit_logs;
create policy "admins can read audit logs"
on public.audit_logs for select
using (private.is_admin());

drop policy if exists "admins can insert audit logs" on public.audit_logs;
create policy "admins can insert audit logs"
on public.audit_logs for insert
with check (private.is_admin());

create or replace function public.get_dining_table_by_qr_token(p_qr_token text)
returns table(
  id uuid,
  code text,
  qr_token text,
  label text,
  is_active boolean
)
language sql
security definer
set search_path = public
as $$
  select dining_tables.id, dining_tables.code, dining_tables.qr_token, dining_tables.label, dining_tables.is_active
  from public.dining_tables
  where dining_tables.qr_token = trim(p_qr_token)
    and dining_tables.is_active = true
  limit 1;
$$;

grant execute on function public.get_dining_table_by_qr_token(text) to anon, authenticated;

create or replace function public.create_table_order(
  p_table_token text,
  p_customer_name text default null,
  p_notes text default null,
  p_payment_method text default 'cash',
  p_payment_status text default 'unpaid',
  p_items jsonb default '[]'::jsonb
)
returns table(order_id uuid, order_number bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_table_id uuid;
  v_session_id uuid;
  v_order_id uuid;
  v_order_number bigint;
  v_subtotal integer := 0;
  v_item jsonb;
  v_menu_entry_id uuid;
  v_menu_name text;
  v_variant_label text;
  v_mix_availability jsonb;
  v_quantity integer;
  v_unit_price integer;
  v_line_total integer;
  v_notes text;
begin
  if p_payment_method not in ('cash', 'edc_bca', 'qris_static', 'dynamic_qris') then
    raise exception 'Invalid payment method';
  end if;

  if p_payment_status not in ('unpaid', 'pending', 'paid', 'failed', 'expired', 'refunded') then
    raise exception 'Invalid payment status';
  end if;

  select id into v_table_id
  from public.dining_tables
  where qr_token = trim(p_table_token)
    and is_active = true;

  if v_table_id is null then
    raise exception 'Invalid table token';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 50 then
    raise exception 'Order must contain 1 to 50 items';
  end if;

  select id into v_session_id
  from public.table_sessions
  where table_id = v_table_id
    and status = 'active'
  order by opened_at desc
  limit 1;

  if v_session_id is null then
    insert into public.table_sessions (table_id, status)
    values (v_table_id, 'active')
    returning id into v_session_id;
  end if;

  insert into public.orders (session_id, table_id, customer_name, notes, status, payment_status, payment_method, subtotal_idr, business_date)
  values (
    v_session_id,
    v_table_id,
    nullif(trim(coalesce(p_customer_name, '')), ''),
    nullif(trim(coalesce(p_notes, '')), ''),
    'new',
    p_payment_status,
    p_payment_method,
    0,
    timezone('Asia/Jakarta', now())::date
  )
  returning id, orders.order_number into v_order_id, v_order_number;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_menu_entry_id := (v_item ->> 'menu_entry_id')::uuid;
    v_variant_label := nullif(trim(coalesce(v_item ->> 'variant_label', '')), '');
    v_quantity := coalesce((v_item ->> 'quantity')::integer, 0);
    v_notes := nullif(trim(coalesce(v_item ->> 'notes', '')), '');

    if v_quantity < 1 or v_quantity > 99 then
      raise exception 'Invalid quantity';
    end if;

    select menu_entries.name, coalesce(menu_entries.price_idr, menu_sections.price_idr, 0), menu_entries.mix_availability
    into v_menu_name, v_unit_price, v_mix_availability
    from public.menu_entries
    join public.menu_sections on menu_sections.id = menu_entries.section_id
    where menu_entries.id = v_menu_entry_id
      and menu_entries.is_available = true
      and menu_sections.is_active = true;

    if v_menu_name is null then
      raise exception 'Menu item is not available';
    end if;

    if v_variant_label is not null and coalesce((v_mix_availability ->> v_variant_label)::boolean, true) = false then
      raise exception 'Menu variant is sold out';
    end if;

    v_line_total := v_unit_price * v_quantity;
    v_subtotal := v_subtotal + v_line_total;

    insert into public.order_items (
      order_id,
      menu_entry_id,
      item_name,
      variant_label,
      quantity,
      unit_price_idr,
      line_total_idr,
      notes
    )
    values (
      v_order_id,
      v_menu_entry_id,
      v_menu_name,
      v_variant_label,
      v_quantity,
      v_unit_price,
      v_line_total,
      v_notes
    );
  end loop;

  update public.orders
  set subtotal_idr = v_subtotal
  where id = v_order_id;

  insert into public.audit_logs (action, entity_type, entity_id, actor_type, metadata)
  values (
    'order_created',
    'order',
    v_order_id,
    'customer',
    jsonb_build_object('table_id', v_table_id, 'session_id', v_session_id, 'subtotal_idr', v_subtotal, 'payment_method', p_payment_method)
  );

  return query select v_order_id, v_order_number;
end;
$$;

grant execute on function public.create_table_order(text, text, text, text, text, jsonb) to anon, authenticated;

create or replace function public.set_order_status(p_order_id uuid, p_status text, p_cancel_reason text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old_status text;
  v_session_id uuid;
begin
  if not private.is_admin() then
    raise exception 'Forbidden';
  end if;

  if p_status not in ('new', 'preparing', 'ready', 'completed', 'canceled') then
    raise exception 'Invalid order status';
  end if;

  if p_status = 'canceled' and nullif(trim(coalesce(p_cancel_reason, '')), '') is null then
    raise exception 'Cancel reason is required';
  end if;

  select status, session_id into v_old_status, v_session_id
  from public.orders
  where id = p_order_id;

  if v_old_status is null then
    raise exception 'Order not found';
  end if;

  update public.orders
  set
    status = p_status,
    cancel_reason = case when p_status = 'canceled' then nullif(trim(coalesce(p_cancel_reason, '')), '') else null end,
    completed_at = case when p_status in ('completed', 'canceled') then coalesce(completed_at, now()) else null end
  where id = p_order_id;

  if v_session_id is not null and p_status in ('completed', 'canceled') then
    update public.table_sessions
    set
      status = case
        when exists (
          select 1
          from public.orders
          where session_id = v_session_id
            and status not in ('completed', 'canceled')
        ) then status
        when p_status = 'canceled' then 'canceled'
        else 'closed'
      end,
      closed_at = case
        when exists (
          select 1
          from public.orders
          where session_id = v_session_id
            and status not in ('completed', 'canceled')
        ) then closed_at
        else now()
      end
    where id = v_session_id;
  end if;

  insert into public.audit_logs (action, entity_type, entity_id, actor_type, actor_user_id, metadata)
  values (
    'order_status_updated',
    'order',
    p_order_id,
    'admin',
    auth.uid(),
    jsonb_build_object('from', v_old_status, 'to', p_status, 'session_id', v_session_id, 'cancel_reason', p_cancel_reason)
  );
end;
$$;

grant execute on function public.set_order_status(uuid, text, text) to authenticated;

create or replace view public.bi_order_facts as
select
  orders.id,
  orders.order_number,
  orders.business_date,
  orders.created_at,
  orders.completed_at,
  orders.status,
  orders.payment_status,
  orders.payment_method,
  orders.subtotal_idr,
  dining_tables.code as table_code,
  dining_tables.label as table_label,
  coalesce(sum(order_items.quantity), 0)::integer as item_quantity
from public.orders
join public.dining_tables on dining_tables.id = orders.table_id
left join public.order_items on order_items.order_id = orders.id
group by orders.id, dining_tables.code, dining_tables.label;

create or replace view public.bi_daily_sales as
select
  business_date,
  count(*) filter (where status = 'completed') as completed_invoice_count,
  count(*) filter (where status = 'canceled') as canceled_invoice_count,
  coalesce(sum(subtotal_idr) filter (where status = 'completed' and payment_status = 'paid'), 0)::integer as paid_sales_idr,
  coalesce(avg(subtotal_idr) filter (where status = 'completed' and payment_status = 'paid'), 0)::integer as average_order_value_idr
from public.orders
group by business_date;

grant select on public.bi_order_facts to authenticated;
grant select on public.bi_daily_sales to authenticated;

insert into public.menu_sections (slug, title, description, display_mode, price_idr, sort_order, is_active)
values
  ('cut-fruits', 'Cut Fruits', 'Fresh sliced fruit cups, ready to grab.', 'compact-list', 15000, 10, true),
  ('blended-juice', 'Blended Juice', 'Classic blended fruit juice, served cold.', 'compact-list', 25000, 20, true),
  ('pre-made-juice', 'Pre-made Juice', 'Bottled blends made fresh for the day.', 'recipe-cards', 30000, 30, true),
  ('cold-pressed-juice', 'Cold-Pressed Juice', '100% murni. Tanpa air, tanpa gula, tanpa sirup.', 'grouped-by-base', 35000, 40, true)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  display_mode = excluded.display_mode,
  price_idr = excluded.price_idr,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

with seed(section_slug, name, ingredients, base_name, accent_color, price_idr, sort_order) as (
  values
    ('cut-fruits', 'Sunkist', array['Sunkist'], null, '#f97316', 15000, 1),
    ('cut-fruits', 'Melon', array['Melon'], null, '#65a30d', 15000, 2),
    ('cut-fruits', 'Pineapple', array['Pineapple'], null, '#eab308', 15000, 3),
    ('cut-fruits', 'Dragon Fruit', array['Dragon Fruit'], null, '#db2777', 15000, 4),
    ('cut-fruits', 'Watermelon', array['Watermelon'], null, '#ef4444', 15000, 5),
    ('cut-fruits', 'Mango', array['Mango'], null, '#f59e0b', 15000, 6),
    ('cut-fruits', 'Green Apple', array['Green Apple'], null, '#16a34a', 15000, 7),
    ('blended-juice', 'Avocado', array['Avocado'], null, '#3f6212', 25000, 1),
    ('blended-juice', 'Sunkist', array['Sunkist'], null, '#f97316', 25000, 2),
    ('blended-juice', 'Melon', array['Melon'], null, '#65a30d', 25000, 3),
    ('blended-juice', 'Pineapple', array['Pineapple'], null, '#eab308', 25000, 4),
    ('blended-juice', 'Guava', array['Guava'], null, '#db2777', 25000, 5),
    ('blended-juice', 'Dragon Fruit', array['Dragon Fruit'], null, '#be185d', 25000, 6),
    ('blended-juice', 'Watermelon', array['Watermelon'], null, '#ef4444', 25000, 7),
    ('blended-juice', 'Strawberry', array['Strawberry'], null, '#e11d48', 25000, 8),
    ('blended-juice', 'Mango', array['Mango'], null, '#f59e0b', 25000, 9),
    ('pre-made-juice', 'Splash Orange', array['Sunkist','Carrot','Green Apple'], null, '#f97316', 30000, 1),
    ('pre-made-juice', 'Pink Heart', array['Guava','Jicama','Watermelon'], null, '#db2777', 30000, 2),
    ('pre-made-juice', 'Yellow Glow', array['Pineapple','Sunkist','Green Apple','Lemon'], null, '#eab308', 30000, 3),
    ('pre-made-juice', 'Berry Happy', array['Strawberry','Sunkist','Watermelon'], null, '#e11d48', 30000, 4),
    ('pre-made-juice', 'Red Love', array['Watermelon','Pineapple','Sunkist'], null, '#dc2626', 30000, 5),
    ('pre-made-juice', 'Maroon Beet', array['Beet','Green Apple','Sunkist'], null, '#7f1d1d', 30000, 6),
    ('pre-made-juice', 'Green Forest', array['Cucumber','Pineapple','Celery','Green Apple','Kale'], null, '#15803d', 30000, 7),
    ('cold-pressed-juice', 'Carrot + Beet', array['Carrot','Beet'], 'Carrot', '#f97316', 35000, 1),
    ('cold-pressed-juice', 'Carrot + Celery', array['Carrot','Celery'], 'Carrot', '#f97316', 35000, 2),
    ('cold-pressed-juice', 'Carrot + Green Apple', array['Carrot','Green Apple'], 'Carrot', '#f97316', 35000, 3),
    ('cold-pressed-juice', 'Celery', array['Celery'], 'Celery', '#16a34a', 35000, 11),
    ('cold-pressed-juice', 'Celery + Melon', array['Celery','Melon'], 'Celery', '#16a34a', 35000, 12),
    ('cold-pressed-juice', 'Celery + Pineapple', array['Celery','Pineapple'], 'Celery', '#16a34a', 35000, 13),
    ('cold-pressed-juice', 'Celery + Green Apple', array['Celery','Green Apple'], 'Celery', '#16a34a', 35000, 14),
    ('cold-pressed-juice', 'Sunkist', array['Sunkist'], 'Sunkist', '#ea580c', 35000, 21),
    ('cold-pressed-juice', 'Sunkist + Carrot', array['Sunkist','Carrot'], 'Sunkist', '#ea580c', 35000, 22),
    ('cold-pressed-juice', 'Sunkist + Pineapple', array['Sunkist','Pineapple'], 'Sunkist', '#ea580c', 35000, 23),
    ('cold-pressed-juice', 'Sunkist + Strawberry', array['Sunkist','Strawberry'], 'Sunkist', '#ea580c', 35000, 24),
    ('cold-pressed-juice', 'Melon', array['Melon'], 'Melon', '#65a30d', 35000, 31),
    ('cold-pressed-juice', 'Melon + Sunkist', array['Melon','Sunkist'], 'Melon', '#65a30d', 35000, 32),
    ('cold-pressed-juice', 'Melon + Green Apple', array['Melon','Green Apple'], 'Melon', '#65a30d', 35000, 33),
    ('cold-pressed-juice', 'Melon + Strawberry', array['Melon','Strawberry'], 'Melon', '#65a30d', 35000, 34),
    ('cold-pressed-juice', 'Pineapple + Melon', array['Pineapple','Melon'], 'Pineapple', '#d97706', 35000, 41),
    ('cold-pressed-juice', 'Pineapple + Sunkist', array['Pineapple','Sunkist'], 'Pineapple', '#d97706', 35000, 42),
    ('cold-pressed-juice', 'Pineapple + Green Apple', array['Pineapple','Green Apple'], 'Pineapple', '#d97706', 35000, 43),
    ('cold-pressed-juice', 'Pineapple + Strawberry', array['Pineapple','Strawberry'], 'Pineapple', '#d97706', 35000, 44),
    ('cold-pressed-juice', 'Watermelon + Sunkist', array['Watermelon','Sunkist'], 'Watermelon', '#ef4444', 35000, 51),
    ('cold-pressed-juice', 'Watermelon + Strawberry', array['Watermelon','Strawberry'], 'Watermelon', '#ef4444', 35000, 52),
    ('cold-pressed-juice', 'Watermelon + Pineapple', array['Watermelon','Pineapple'], 'Watermelon', '#ef4444', 35000, 53),
    ('cold-pressed-juice', 'Guava + Beet', array['Guava','Beet'], 'Guava', '#db2777', 35000, 61),
    ('cold-pressed-juice', 'Guava + Sunkist', array['Guava','Sunkist'], 'Guava', '#db2777', 35000, 62),
    ('cold-pressed-juice', 'Guava + Pineapple', array['Guava','Pineapple'], 'Guava', '#db2777', 35000, 63),
    ('cold-pressed-juice', 'Guava + Green Apple', array['Guava','Green Apple'], 'Guava', '#db2777', 35000, 64),
    ('cold-pressed-juice', 'Guava + Watermelon', array['Guava','Watermelon'], 'Guava', '#db2777', 35000, 65),
    ('cold-pressed-juice', 'Beet + Carrot', array['Beet','Carrot'], 'Beet', '#be123c', 35000, 71),
    ('cold-pressed-juice', 'Beet + Pineapple', array['Beet','Pineapple'], 'Beet', '#be123c', 35000, 72),
    ('cold-pressed-juice', 'Beet + Green Apple', array['Beet','Green Apple'], 'Beet', '#be123c', 35000, 73)
)
insert into public.menu_entries (section_id, name, ingredients, base_name, accent_color, price_idr, sort_order, is_available)
select menu_sections.id, seed.name, seed.ingredients, seed.base_name, seed.accent_color, seed.price_idr, seed.sort_order, true
from seed
join public.menu_sections on menu_sections.slug = seed.section_slug
where not exists (
  select 1
  from public.menu_entries
  where menu_entries.section_id = menu_sections.id
    and menu_entries.name = seed.name
);

update public.menu_entries
set benefit = case name
  when 'Splash Orange' then 'Vitamin C dan beta-carotene untuk bantu jaga imun dan kulit tetap fresh.'
  when 'Pink Heart' then 'Rasa ringan, juicy, dan tinggi antioksidan untuk refresh harian.'
  when 'Yellow Glow' then 'Bright citrus blend untuk rasa segar dan bantu pencernaan.'
  when 'Berry Happy' then 'Manis-asam segar dengan antioksidan dari berry dan hidrasi watermelon.'
  when 'Red Love' then 'Hydrating, tropical, dan ringan untuk booster energi siang hari.'
  when 'Maroon Beet' then 'Earthy fresh untuk stamina, sirkulasi, dan rasa yang tetap balanced.'
  when 'Green Forest' then 'Green blend untuk detox ringan, mineral, dan rasa clean.'
  else benefit
end
where section_id = (select id from public.menu_sections where slug = 'pre-made-juice');

delete from public.menu_entries
where section_id = (select id from public.menu_sections where slug = 'cold-pressed-juice');

with cold_pressed_base(section_slug, name, ingredients, base_name, benefit, mix_notes, category_slug, accent_color, price_idr, sort_order) as (
  values
    ('cold-pressed-juice', 'Carrot', array['Green Apple','Celery','Sunkist'], 'Carrot', 'Mata dan kulit', '{"Green Apple":"Rasa lebih crisp dan bantu tambah antioksidan.","Celery":"Lebih clean dan ringan untuk detox harian.","Sunkist":"Vitamin C bikin carrot lebih bright dan fresh."}'::jsonb, 'roots-detox', '#f97316', 35000, 1),
    ('cold-pressed-juice', 'Beet', array['Green Apple','Carrot','Pineapple'], 'Beet', 'Stamina', '{"Green Apple":"Menyeimbangkan earthy beet dengan rasa segar.","Carrot":"Dobel roots untuk stamina dan beta-carotene.","Pineapple":"Rasa tropical dan bantu pencernaan."}'::jsonb, 'roots-detox', '#be123c', 35000, 2),
    ('cold-pressed-juice', 'Celery', array['Original','Green Apple','Pineapple','Melon'], 'Celery', 'Deep detox', '{"Original":"Celery murni tanpa campuran untuk rasa paling clean dan ringan.","Green Apple":"Lebih crisp, segar, dan mudah diminum.","Pineapple":"Manis-asam tropical untuk bantu pencernaan.","Melon":"Lebih ringan dan hydrating."}'::jsonb, 'roots-detox', '#16a34a', 35000, 3),
    ('cold-pressed-juice', 'Sunkist', array['Original','Green Apple','Pineapple','Strawberry','Watermelon','Melon','Beet'], 'Sunkist', 'Imun kuat', '{"Original":"Sunkist murni untuk citrus vitamin C yang clean dan bright.","Green Apple":"Crisp dan fresh untuk balance rasa citrus.","Pineapple":"Tropical vitamin C dengan rasa lebih juicy.","Strawberry":"Antioksidan berry dan rasa manis-asam.","Watermelon":"Lebih hydrating dan ringan.","Melon":"Rasa soft, fresh, dan tidak terlalu asam.","Beet":"Tambahan earthy untuk stamina dan warna lebih bold."}'::jsonb, 'vitamin-c-booster', '#ea580c', 35000, 4),
    ('cold-pressed-juice', 'Pineapple', array['Original','Melon','Green Apple','Guava','Sunkist','Strawberry'], 'Pineapple', 'Pencernaan', '{"Original":"Pineapple murni dengan rasa tropical dan karakter manis-asam.","Melon":"Lebih smooth dan hydrating.","Green Apple":"Crisp acidity untuk rasa lebih segar.","Guava":"Antioksidan dan body rasa lebih tebal.","Sunkist":"Extra citrus untuk vitamin C booster.","Strawberry":"Berry note yang manis-asam."}'::jsonb, 'vitamin-c-booster', '#d97706', 35000, 5),
    ('cold-pressed-juice', 'Guava', array['Green Apple','Sunkist','Strawberry','Beet','Pineapple'], 'Guava', 'Antioksidan', '{"Green Apple":"Lebih fresh dan ringan.","Sunkist":"Tambahan citrus untuk imun.","Strawberry":"Antioksidan berry dan aroma lebih fruity.","Beet":"Lebih bold untuk stamina.","Pineapple":"Tropical dan bantu pencernaan."}'::jsonb, 'vitamin-c-booster', '#db2777', 35000, 6),
    ('cold-pressed-juice', 'Watermelon', array['Original','Sunkist','Strawberry','Green Apple','Pineapple'], 'Watermelon', 'Segar', '{"Original":"Watermelon murni untuk hidrasi yang ringan dan juicy.","Sunkist":"Citrus fresh untuk rasa lebih lively.","Strawberry":"Berry note dan antioksidan.","Green Apple":"Crisp dan balance manis watermelon.","Pineapple":"Tropical, juicy, dan segar."}'::jsonb, 'hydration', '#ef4444', 35000, 7),
    ('cold-pressed-juice', 'Melon', array['Original','Sunkist','Strawberry','Green Apple','Watermelon'], 'Melon', 'Hidrasi ringan', '{"Original":"Melon murni untuk rasa lembut, dingin, dan hydrating.","Sunkist":"Citrus lift untuk rasa lebih fresh.","Strawberry":"Manis-asam ringan dengan antioksidan.","Green Apple":"Crisp dan clean.","Watermelon":"Extra hydrating dan juicy."}'::jsonb, 'hydration', '#65a30d', 35000, 8),
    ('cold-pressed-juice', 'Cucumber', array['Original','Pineapple','Celery','Green Apple'], 'Cucumber', 'Cooling detox', '{"Original":"Cucumber murni untuk rasa clean, ringan, dan cooling.","Pineapple":"Lebih tropical dan mudah diminum.","Celery":"Karakter green lebih kuat untuk detox harian.","Green Apple":"Crisp dan fresh untuk balance rasa cucumber."}'::jsonb, 'hydration', '#0f9f6e', 35000, 9)
)
insert into public.menu_entries (section_id, name, ingredients, base_name, benefit, mix_notes, mix_image_urls, category_slug, accent_color, price_idr, sort_order, is_available)
select menu_sections.id, cold_pressed_base.name, cold_pressed_base.ingredients, cold_pressed_base.base_name, cold_pressed_base.benefit, cold_pressed_base.mix_notes, '{}'::jsonb, cold_pressed_base.category_slug, cold_pressed_base.accent_color, cold_pressed_base.price_idr, cold_pressed_base.sort_order, true
from cold_pressed_base
join public.menu_sections on menu_sections.slug = cold_pressed_base.section_slug;

insert into public.dining_tables (code, label, is_active)
select 'T' || lpad(value::text, 2, '0'), 'Table ' || lpad(value::text, 2, '0'), true
from generate_series(1, 12) as value
on conflict (code) do nothing;
