alter table public.menu_entries
add column if not exists mix_image_urls jsonb not null default '{}'::jsonb;

delete from public.menu_entries
where section_id = (select id from public.menu_sections where slug = 'cold-pressed-juice');

with cold_pressed_base(section_slug, name, ingredients, base_name, benefit, mix_notes, category_slug, accent_color, price_idr, sort_order) as (
  values
    ('cold-pressed-juice', 'Carrot', array['Green Apple','Celery','Sunkist'], 'Carrot', 'Mata dan kulit', '{"Green Apple":"Rasa lebih crisp dan bantu tambah antioksidan.","Celery":"Lebih clean dan ringan untuk detox harian.","Sunkist":"Vitamin C bikin carrot lebih bright dan fresh."}'::jsonb, 'roots-detox', '#f97316', 35000, 1),
    ('cold-pressed-juice', 'Beet', array['Green Apple','Carrot','Pineapple'], 'Beet', 'Stamina', '{"Green Apple":"Menyeimbangkan earthy beet dengan rasa segar.","Carrot":"Dobel roots untuk stamina dan beta-carotene.","Pineapple":"Rasa tropical dan bantu pencernaan."}'::jsonb, 'roots-detox', '#be123c', 35000, 2),
    ('cold-pressed-juice', 'Celery', array['Original','Green Apple','Pineapple','Melon'], 'Celery', 'Deep detox', '{"Original":"Celery murni tanpa campuran untuk rasa paling clean dan ringan.","Green Apple":"Lebih crisp, segar, dan mudah diminum.","Pineapple":"Manis-asam tropical untuk bantu pencernaan.","Melon":"Lebih ringan dan hydrating."}'::jsonb, 'roots-detox', '#16a34a', 35000, 3),
    ('cold-pressed-juice', 'Sunkist', array['Original','Green Apple','Pineapple','Strawberry','Watermelon','Melon','Beet'], 'Sunkist', 'Imun kuat', '{"Original":"Sunkist murni untuk citrus vitamin C yang clean dan bright.","Green Apple":"Crisp dan fresh untuk balance rasa citrus.","Pineapple":"Tropical vitamin C dengan rasa lebih juicy.","Strawberry":"Antioksidan berry dan rasa manis-asam.","Watermelon":"Lebih hydrating dan ringan.","Melon":"Rasa soft, fresh, dan tidak terlalu asam.","Beet":"Tambahan earthy untuk stamina dan warna lebih bold."}'::jsonb, 'vitamin-c-booster', '#ea580c', 35000, 4),
    ('cold-pressed-juice', 'Pineapple', array['Original','Melon','Green Apple','Guava','Sunkist','Strawberry'], 'Pineapple', 'Pencernaan', '{"Original":"Pineapple murni dengan rasa tropical dan karakter manis-asam.","Melon":"Lebih smooth dan hydrating.","Green Apple":"Crisp acidity untuk rasa lebih segar.","Guava":"Antioksidan dan body rasa lebih tebal.","Sunkist":"Extra citrus untuk vitamin C booster.","Strawberry":"Berry note yang manis-asam."}'::jsonb, 'vitamin-c-booster', '#d97706', 35000, 5),
    ('cold-pressed-juice', 'Guava', array['Green Apple','Sunkist','Strawberry','Beet','Pineapple'], 'Guava', 'Antioksidan', '{"Green Apple":"Lebih fresh dan ringan.","Sunkist":"Tambahan citrus untuk imun.","Strawberry":"Antioksidan berry dan aroma lebih fruity.","Beet":"Lebih bold untuk stamina.","Pineapple":"Tropical dan bantu pencernaan."}'::jsonb, 'vitamin-c-booster', '#db2777', 35000, 6),
    ('cold-pressed-juice', 'Watermelon', array['Original','Sunkist','Strawberry','Green Apple','Pineapple'], 'Watermelon', 'Segar', '{"Original":"Watermelon murni untuk hidrasi yang ringan dan juicy.","Sunkist":"Citrus fresh untuk rasa lebih lively.","Strawberry":"Berry note dan antioksidan.","Green Apple":"Crisp dan balance manis watermelon.","Pineapple":"Tropical, juicy, dan segar."}'::jsonb, 'hydration', '#ef4444', 35000, 7),
    ('cold-pressed-juice', 'Melon', array['Original','Sunkist','Strawberry','Green Apple','Watermelon'], 'Melon', 'Hidrasi ringan', '{"Original":"Melon murni untuk rasa lembut, dingin, dan hydrating.","Sunkist":"Citrus lift untuk rasa lebih fresh.","Strawberry":"Manis-asam ringan dengan antioksidan.","Green Apple":"Crisp dan clean.","Watermelon":"Extra hydrating dan juicy."}'::jsonb, 'hydration', '#65a30d', 35000, 8),
    ('cold-pressed-juice', 'Cucumber', array['Original','Pineapple','Celery','Green Apple'], 'Cucumber', 'Cooling detox', '{"Original":"Cucumber murni untuk rasa clean, ringan, dan cooling.","Pineapple":"Lebih tropical dan mudah diminum.","Celery":"Karakter green lebih kuat untuk detox harian.","Green Apple":"Crisp dan fresh untuk balance rasa cucumber."}'::jsonb, 'hydration', '#0f9f6e', 35000, 9)
)
insert into public.menu_entries (section_id, name, ingredients, base_name, benefit, mix_notes, mix_image_urls, category_slug, accent_color, price_idr, sort_order, is_available)
select menu_sections.id, cold_pressed_base.name, cold_pressed_base.ingredients, cold_pressed_base.base_name, cold_pressed_base.benefit, cold_pressed_base.mix_notes, '{}'::jsonb, cold_pressed_base.category_slug, cold_pressed_base.accent_color, cold_pressed_base.price_idr, cold_pressed_base.sort_order, true
from cold_pressed_base
join public.menu_sections on menu_sections.slug = cold_pressed_base.section_slug;
